//Search constants
export const FETCHING_SUGGESTIONS = 'FETCHING_SUGGESTIONS';
export const FETCHING_SUGGESTIONS_SUCCESS = 'FETCHING_SUGGESTIONS_SUCCESS';
export const FETCHING_SUGGESTIONS_FAILURE = 'FETCHING_SUGGESTIONS_FAILURE';
export const FETCHING_RESULTS = 'FETCHING_RESULTS';
export const FETCHING_RESULTS_SUCCESS = 'FETCHING_RESULTS_SUCCESS';
export const FETCHING_RESULTS_FAILURE = 'FETCHING_RESULTS_FAILURE';
