//Search constants
export const FETCHING_PLACE = 'FETCHING_PLACE';
export const FETCHING_PLACE_SUCCESS = 'FETCHING_PLACE_SUCCESS';
export const FETCHING_PLACE_FAILURE = 'FETCHING_PLACE_FAILURE';
export const FETCHING_RESULTS = 'FETCHING_RESULTS';
export const FETCHING_RESULTS_SUCCESS = 'FETCHING_RESULTS_SUCCESS';
export const FETCHING_RESULTS_FAILURE = 'FETCHING_RESULTS_FAILURE';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const RESET_SEARCH = 'RESET_SEARCH';
export const SET_PLACE = 'SET_PLACE';
